ORIGIN		:=	github.com/ed006949
NAME		:=	rmm26
VERSION		:=	0.0.1

PACKAGE		:=	${ORIGIN}/${NAME}

TARGET		:=	${NAME}

COMMAND_LINE	:=	--config="./etc/${NAME}.json" --dry-run true
#COMMAND_LINE	:=	--config="./etc/${NAME}.json"

GITIGNORE_URL	:=	https://www.toptal.com/developers/gitignore/api/go,linux,macos,windows,jetbrains,jetbrains+all,jetbrains+iml,visualstudiocode,xcode,xcodeinjection

#GPG_KEY		:=	A2FC1F3EF2AC4B53

#
#
#
#
